pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "flask-app:latest"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/preetishinge/Enterprise-CI-CD-K8s-DevSecOps'
            }
        }
        stage('SonarQube Scan') {
            steps {
                sh 'sonar-scanner -Dsonar.projectKey=FlaskApp -Dsonar.sources=src/app -Dsonar.host.url=http://localhost:9000 -Dsonar.login=<your-token>'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE ./docker'
            }
        }
        stage('Security Scan') {
            steps {
                sh 'trivy image $DOCKER_IMAGE'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
    post {
        success { echo 'Pipeline succeeded!' }
        failure { echo 'Pipeline failed. Check logs.' }
    }
}
